=== jegiraldp/XML/ejercicios/xml2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT fichero (cotizacion+)>
<!ELEMENT cotizacion (nombre+, mercado, fecha)>
<!ATTLIST cotizacion
	id CDATA #REQUIRED
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mercado (#PCDATA)>
<!ELEMENT fecha (year, mes, dia)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT %n; (#PCDATA)>

=== jegiraldp/XML/ejercicios/xml2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--<!DOCTYPE fichero SYSTEM "xml2.dtd">-->
<fichero>
	<cotizacion id="1">
		<nombre>Cotizacion de pcs</nombre>
		<mercado>hola</mercado>
		<fecha>
			<year>2006</year>
			<mes>Marzo</mes>
			<dia>hola</dia>
		</fecha>
	</cotizacion>
</fichero>
